from playsound import playsound
import time, datetime
import os
import subprocess
import xlsxwriter
import re


TC_Name = "GeneralSettings"
cwd = os.getcwd()
reports = r''+cwd+'/Reports/'+TC_Name+''
if not os.path.exists(reports):
    os.makedirs(reports)


screenshots = r''+cwd+'/Screenshots/'+TC_Name+''
if not os.path.exists(screenshots):
    os.makedirs(screenshots)

row = 0
col = 0
ts_report = time.time()
time_stamp_report = datetime.datetime.fromtimestamp(ts_report).strftime('-%d-%m-%Y-%H-%M-%S')
workbook = xlsxwriter.Workbook("Reports/"+TC_Name+"/"+TC_Name+""+time_stamp_report+".xlsx")
worksheet = workbook.add_worksheet()
worksheet.write(row, col, "Time_Stamp")
worksheet.write(row, col + 1, "Platform")
worksheet.write(row, col + 2, "BSP_Version")
worksheet.write(row, col + 3, "Expected")
worksheet.write(row, col + 4, "Actual")
worksheet.write(row, col + 5, "Confidence_Value")
worksheet.write(row, col + 6, "Result")
row += 1


def voice_commands(text):
    global row
    global col
    adb_clear = "adb shell logcat -c"
    os.system(adb_clear)
    adb_devinfo = "adb shell getprop ro.product.version.software"
    adb_process = subprocess.Popen(adb_devinfo, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_bspversion = adb_process.communicate()[0]
    adb_bspversion = adb_bspversion.decode("utf-8")
    adb_platform = re.search(r'^\w+', str(adb_bspversion)).group(0)

    try:
        playsound('Tones/'+text+'.wav')
        time.sleep(1)
    except:
        playsound('Tones/'+text+'.mp3')
        time.sleep(1)
    ts = time.time()
    time_stamp = datetime.datetime.fromtimestamp(ts).strftime('-%d-%m-%Y-%H-%M-%S')
    adb_screenshot = "adb exec-out screencap -p > Screenshots/\""+TC_Name+"\"/\""+text+"\""+time_stamp+".png"
    os.system(adb_screenshot)
    adb_fetch = "adb shell logcat -d | find \"(ACCEPTED)\""
    adb_ps = subprocess.Popen(adb_fetch, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_result = adb_ps.communicate()[0]
    adb_result = adb_result.decode("utf-8")
    try:
        adb_confidence = re.search(r"\[(.*?)\]", adb_result).group(1)
        adb_timestamp = re.search(r"\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}", adb_result).group(0)
        adb_result = re.search(r"\)(.*?)\[", adb_result).group(1)
    except AttributeError:
        adb_result = ""
        adb_confidence = ""
        adb_timestamp = ""
    adb_result = adb_result[1:-1]
    print(text)
    print(adb_result)
    if text.lower() == adb_result.lower():
        print(""+text+" -> PASS")
        assert adb_result.lower() == text.lower()
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, adb_result)
        worksheet.write(row, col + 5, adb_confidence)
        worksheet.write(row, col + 6, "PASS")
        row += 1
    else:
        print(""+text+" -> FAIL")
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, adb_result)
        worksheet.write(row, col + 5, adb_confidence)
        worksheet.write(row, col + 6, "FAIL")
        row += 1
        workbook.close()  # will save the result till it executed in current script
        assert adb_result.lower() == text.lower()  # will terminate execution if failure occurs


def close_recent_applications():
    try:
        playsound('Tones/Recent Applications.wav')
        time.sleep(3)
        playsound('Tones/Dismiss All.wav')
        time.sleep(2)
        playsound('Tones/Navigate Back.wav')
    except:
        playsound('Tones/Recent Applications.mp3')
        time.sleep(3)
        playsound('Tones/Dismiss All.mp3')
        time.sleep(2)
        playsound('Tones/Navigate Back.mp3')


def device_wakeup():
    adb_wakeup = "adb shell input keyevent KEYCODE_WAKEUP"
    os.system(adb_wakeup)

def test_General_Setings():
    device_wakeup()
    close_recent_applications()
    time.sleep(2)

    # Network and Internet options testing
    voice_commands("Navigate Home")
    time.sleep(2)
    voice_commands("My Programs")
    time.sleep(2)
    voice_commands("Settings")
    time.sleep(4)
    voice_commands("Network and Internet")
    time.sleep(2)
    voice_commands("Wireless Networks")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(3)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Connected devices")
    time.sleep(2)
    voice_commands("USB")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Pair new device")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Connection preferences")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Apps and notifications")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Battery")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Display")
    time.sleep(2)
    voice_commands("Brightness level")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Night Light")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Screen timeout")
    time.sleep(2)
    voice_commands("30 seconds")
    time.sleep(2)
    voice_commands("Screen timeout")
    time.sleep(2)
    voice_commands("5 minutes")
    time.sleep(2)
    voice_commands("Screen timeout")
    time.sleep(2)
    voice_commands("10 minutes")
    time.sleep(2)
    voice_commands("Screen timeout")
    time.sleep(2)
    voice_commands("30 minutes")
    time.sleep(2)
    voice_commands("Screen timeout")
    time.sleep(2)
    voice_commands("CANCEL")
    time.sleep(2)
    voice_commands("Page Down")
    time.sleep(2)
    voice_commands("Advanced")
    time.sleep(2)
    voice_commands("Font size")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Sound")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Page down")
    time.sleep(2)
    voice_commands("Storage")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Privacy")
    time.sleep(2)
    voice_commands("Accessibility usage")
    time.sleep(2)
    voice_commands("ok")
    time.sleep(2)
    voice_commands("Permission manager")
    time.sleep(2)
    voice_commands("navigate back")
    time.sleep(2)
    voice_commands("Show passwords")
    time.sleep(2)
    voice_commands("Show passwords")
    time.sleep(2)
    voice_commands("Lock screen")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Location")
    time.sleep(2)
    voice_commands("Use Location")
    time.sleep(2)
    voice_commands("Use Location")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Security")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Accounts")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Accessibility")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Select item 7")
    time.sleep(2)
    voice_commands("Bluetooth Mode")
    time.sleep(2)
    voice_commands("Bluetooth Mode")
    time.sleep(2)
    voice_commands("Storage Mode")
    time.sleep(2)
    voice_commands("Storage Mode")
    time.sleep(2)
    voice_commands("CameraLow light")
    time.sleep(2)
    voice_commands("CameraLow light")
    time.sleep(2)
    voice_commands("CameraField of View")
    time.sleep(2)
    voice_commands("CameraField of View")
    time.sleep(2)
    voice_commands("CameraImage Stabilization")
    time.sleep(2)
    voice_commands("CameraImage Stabilization")
    time.sleep(2)
    voice_commands("Navigate Back")
    time.sleep(2)
    voice_commands("Page down")
    time.sleep(2)
    voice_commands("System")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("About Device")
    time.sleep(2)
    voice_commands("Device name")
    time.sleep(2)
    voice_commands("navigate Back")
    time.sleep(2)
    voice_commands("Ok")
    time.sleep(2)
    voice_commands("Cancel")
    time.sleep(2)
    voice_commands("Emergency information")
    time.sleep(2)
    voice_commands("navigate Back")
    time.sleep(2)
    voice_commands("Model")
    time.sleep(2)
    voice_commands("navigate Back")
    time.sleep(2)
    voice_commands("Page Down")
    time.sleep(2)
    voice_commands("Android version")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)
    voice_commands("Page Down")
    time.sleep(2)
    voice_commands("Build number")
    time.sleep(2)
    voice_commands("Navigate back")
    time.sleep(2)

    workbook.close()