from playsound import playsound
import time, datetime
import os
import subprocess
import xlsxwriter
import re


TC_Name = "GeneralSettings_Spanish"
cwd = os.getcwd()
reports = r''+cwd+'/Reports/'+TC_Name+''
if not os.path.exists(reports):
    os.makedirs(reports)

ts_screenshot = time.time()
time_stamp_screenshot = datetime.datetime.fromtimestamp(ts_screenshot).strftime('-%d-%m-%Y-%H-%M-%S')
screenshots = r''+cwd+'/Screenshots/'+TC_Name+''+time_stamp_screenshot+''
if not os.path.exists(screenshots):
    os.makedirs(screenshots)


row = 0
col = 0
ts_report = time.time()
time_stamp_report = datetime.datetime.fromtimestamp(ts_report).strftime('-%d-%m-%Y-%H-%M-%S')
workbook = xlsxwriter.Workbook("Reports/"+TC_Name+"/"+TC_Name+""+time_stamp_report+".xlsx")
worksheet = workbook.add_worksheet()
worksheet.write(row, col, "Time_Stamp")
worksheet.write(row, col + 1, "Platform")
worksheet.write(row, col + 2, "BSP_Version")
worksheet.write(row, col + 3, "English_Command")
worksheet.write(row, col + 4, "Expected_Result")
worksheet.write(row, col + 5, "Actual_Result")
worksheet.write(row, col + 6, "Confidence_Value")
worksheet.write(row, col + 7, "Result")
row += 1


def voice_commands(text, text_log):
    global row
    global col
    adb_clear = "adb shell logcat -c"
    os.system(adb_clear)
    adb_devinfo = "adb shell getprop ro.product.version.software"
    adb_process = subprocess.Popen(adb_devinfo, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_bspversion = adb_process.communicate()[0]
    adb_bspversion = adb_bspversion.decode("utf-8")
    adb_platform = re.search(r'^\w+', str(adb_bspversion)).group(0)
    try:
        playsound('Tones/'+text+'.wav')
        time.sleep(1)
    except:
        playsound('Tones/'+text+'.mp3')
        time.sleep(1)
    ts = time.time()
    time_stamp = datetime.datetime.fromtimestamp(ts).strftime('-%d-%m-%Y-%H-%M-%S')
    adb_screenshot = "adb exec-out screencap -p > Screenshots/\""+TC_Name+""+time_stamp_screenshot+"\"/\""+text+"\""+time_stamp+".png"
    os.system(adb_screenshot)
    adb_fetch = "adb shell logcat -d | find \"(ACCEPTED)\""
    adb_ps = subprocess.Popen(adb_fetch, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_result = adb_ps.communicate()[0]
    adb_result = adb_result.decode("utf-8")
    try:
        adb_confidence = re.search(r"\[(.*?)\]", adb_result).group(1)
        adb_timestamp = re.search(r"\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}", adb_result).group(0)
        adb_result = re.search(r"\)(.*?)\[", adb_result).group(1)
    except AttributeError:
        adb_result = ""
        adb_confidence = ""
        adb_timestamp = ""
    adb_result = adb_result[1:-1]

    if text_log.lower() == adb_result.lower():
        print(""+text_log+" -> PASS")
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, text_log)
        worksheet.write(row, col + 5, adb_result)
        worksheet.write(row, col + 6, adb_confidence)
        worksheet.write(row, col + 7, "PASS")
        row += 1
    else:
        print(""+text_log+" -> FAIL")
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, text_log)
        worksheet.write(row, col + 5, adb_result)
        worksheet.write(row, col + 6, adb_confidence)
        worksheet.write(row, col + 7, "FAIL")
        workbook.close()  # will save the result till it executed in current script
        assert adb_result.lower() == text.lower()  # will terminate execution if failure occurs
        row += 1


def close_recent_applications():
    try:
        playsound('Tones/Recent Applications.wav')
        time.sleep(3)
        playsound('Tones/Dismiss All.wav')
        time.sleep(2)
        playsound('Tones/Navigate Back.wav')
    except:
        playsound('Tones/Recent Applications.mp3')
        time.sleep(3)
        playsound('Tones/Dismiss All.mp3')
        time.sleep(2)
        playsound('Tones/Navigate Back.mp3')


def device_wakeup():
    adb_wakeup = "adb shell input keyevent KEYCODE_WAKEUP"
    os.system(adb_wakeup)

def test_General_Setings_Spanish():

    device_wakeup()
    close_recent_applications()
    time.sleep(2)

    # Network and Internet options testing
    voice_commands("Navigate Home","Regresar a inicio")
    time.sleep(2)
    voice_commands("My Programs","Mis programas")
    time.sleep(2)
    voice_commands("Settings","Configuración")
    time.sleep(4)
    voice_commands("Network and Internet","Internet y redes")
    time.sleep(2)
    voice_commands("Wi Fi","Wi Fi")
    time.sleep(5)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(3)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Connected devices","Dispositivos conectados")
    time.sleep(2)
    voice_commands("Pair new device","Sincronizar dispositivo nuevo")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Connection preferences","Preferencias de conexión")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    #voice_commands("Apps and notifications","Mostrar notificaciones")
    #time.sleep(2)
    #voice_commands("Navigate Back","Ir atrás")
    #time.sleep(2)
    voice_commands("Battery","Batería")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Display","Pantalla")
    time.sleep(2)
    voice_commands("Brightness level","Nivel de brillo")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Night Light","Luz nocturna")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Screen timeout","Tiempo de espera de la pantalla")
    time.sleep(2)
    voice_commands("30 seconds","30 segundos")
    time.sleep(2)
    voice_commands("Screen timeout","Tiempo de espera de la pantalla")
    time.sleep(2)
    voice_commands("5 minutes","5 minutos")
    time.sleep(2)
    voice_commands("Screen timeout","Tiempo de espera de la pantalla")
    time.sleep(2)
    voice_commands("10 minutes","10 minutos")
    time.sleep(2)
    voice_commands("Screen timeout","Tiempo de espera de la pantalla")
    time.sleep(2)
    voice_commands("30 minutes","30 minutos")
    time.sleep(2)
    voice_commands("Screen timeout","Tiempo de espera de la pantalla")
    time.sleep(2)
    voice_commands("CANCEL","CANCELAR")
    time.sleep(2)
    voice_commands("Page Down","Bajar página")
    time.sleep(2)
    voice_commands("Advanced","Opciones avanzadas")
    time.sleep(2)
    voice_commands("Font size","Tamaño de fuente")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Sound","Sonido")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Page down","Bajar página")
    time.sleep(2)
    voice_commands("Storage","Almacenamiento")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Privacy","Privacidad")
    time.sleep(2)
    voice_commands("Accessibility usage","Uso de accesibilidad")
    time.sleep(2)
    voice_commands("Accept","Aceptar")
    time.sleep(2)
    voice_commands("Permission manager","Administrador de permisos")
    time.sleep(2)
    voice_commands("navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Show passwords","Mostrar contraseñas")
    time.sleep(2)
    voice_commands("Show passwords","Mostrar contraseñas")
    time.sleep(2)
    voice_commands("Lock screen","Pantalla de bloqueo")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Location","Ubicación")
    time.sleep(2)
    voice_commands("Use Location","Usar ubicación")
    time.sleep(2)
    voice_commands("Use Location","Usar ubicación")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Security","Seguridad")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Accounts","Cuentas")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Accessibility","Accesibilidad")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Realwear","RealWear")
    time.sleep(2)
    voice_commands("Bluetooth Mode","Modo bluetooth")
    time.sleep(3)
    voice_commands("Bluetooth Mode","Modo bluetooth")
    time.sleep(3)
    voice_commands("Storage Mode","Modo de almacenamiento")
    time.sleep(3)
    voice_commands("Storage Mode","Modo de almacenamiento")
    time.sleep(3)
    voice_commands("Camera Low light","Cámara Luz Baja")
    time.sleep(2)
    voice_commands("Camera Low light","Cámara Luz Baja")
    time.sleep(2)
    voice_commands("Camera Field of View","Cámara campo de visión")
    time.sleep(2)
    voice_commands("Camera Field of View","Cámara campo de visión")
    time.sleep(2)
    voice_commands("Camera Image Stabilization","Cámara Estabilización de imagen")
    time.sleep(2)
    voice_commands("Camera Image Stabilization","Cámara Estabilización de imagen")
    time.sleep(2)
    voice_commands("Navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Page down","Bajar página")
    time.sleep(2)
    voice_commands("System","Sistema")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("About Device","Acerca del dispositivo")
    time.sleep(2)
    voice_commands("Device name","Nombre del dispositivo")
    time.sleep(2)
    voice_commands("navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Accept","Aceptar")
    time.sleep(2)
    voice_commands("Cancel","CANCELAR")
    time.sleep(2)
    voice_commands("Emergency information","Información de emergencia")
    time.sleep(2)
    voice_commands("navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Model","Modelo")
    time.sleep(2)
    voice_commands("navigate Back","Ir atrás")
    time.sleep(2)
    voice_commands("Page Down","Bajar página")
    time.sleep(2)
    voice_commands("Android version","Versión de Android")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)
    voice_commands("Page Down","Bajar página")
    time.sleep(2)
    voice_commands("Build number","Número de compilación")
    time.sleep(2)
    voice_commands("Navigate back","Ir atrás")
    time.sleep(2)

    workbook.close()