from playsound import playsound
import time, datetime
import os
import subprocess
import xlsxwriter
import re


TC_Name = "GeneralSettings_French"
cwd = os.getcwd()
reports = r''+cwd+'/Reports/'+TC_Name+''
if not os.path.exists(reports):
    os.makedirs(reports)

ts_screenshot = time.time()
time_stamp_screenshot = datetime.datetime.fromtimestamp(ts_screenshot).strftime('-%d-%m-%Y-%H-%M-%S')
screenshots = r''+cwd+'/Screenshots/'+TC_Name+''+time_stamp_screenshot+''
if not os.path.exists(screenshots):
    os.makedirs(screenshots)


row = 0
col = 0
ts_report = time.time()
time_stamp_report = datetime.datetime.fromtimestamp(ts_report).strftime('-%d-%m-%Y-%H-%M-%S')
workbook = xlsxwriter.Workbook("Reports/"+TC_Name+"/"+TC_Name+""+time_stamp_report+".xlsx")
worksheet = workbook.add_worksheet()
worksheet.write(row, col, "Time_Stamp")
worksheet.write(row, col + 1, "Platform")
worksheet.write(row, col + 2, "BSP_Version")
worksheet.write(row, col + 3, "English_Command")
worksheet.write(row, col + 4, "Expected_Result")
worksheet.write(row, col + 5, "Actual_Result")
worksheet.write(row, col + 6, "Confidence_Value")
worksheet.write(row, col + 7, "Result")
row += 1


def voice_commands(text, text_log):
    global row
    global col
    adb_clear = "adb shell logcat -c"
    os.system(adb_clear)
    adb_devinfo = "adb shell getprop ro.product.version.software"
    adb_process = subprocess.Popen(adb_devinfo, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_bspversion = adb_process.communicate()[0]
    adb_bspversion = adb_bspversion.decode("utf-8")
    adb_platform = re.search(r'^\w+', str(adb_bspversion)).group(0)
    try:
        playsound('Tones/'+text+'.wav')
        time.sleep(1)
    except:
        playsound('Tones/'+text+'.mp3')
        time.sleep(1)
    ts = time.time()
    time_stamp = datetime.datetime.fromtimestamp(ts).strftime('-%d-%m-%Y-%H-%M-%S')
    adb_screenshot = "adb exec-out screencap -p > Screenshots/\""+TC_Name+""+time_stamp_screenshot+"\"/\""+text+"\""+time_stamp+".png"
    os.system(adb_screenshot)
    adb_fetch = "adb shell logcat -d | find \"(ACCEPTED)\""
    adb_ps = subprocess.Popen(adb_fetch, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    adb_result = adb_ps.communicate()[0]
    adb_result = adb_result.decode("utf-8")
    try:
        adb_confidence = re.search(r"\[(.*?)\]", adb_result).group(1)
        adb_timestamp = re.search(r"\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}", adb_result).group(0)
        adb_result = re.search(r"\)(.*?)\[", adb_result).group(1)
    except AttributeError:
        adb_result = ""
        adb_confidence = ""
        adb_timestamp = ""
    adb_result = adb_result[1:-1]

    if text_log.lower() == adb_result.lower():
        print(""+text_log+" -> PASS")
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, text_log)
        worksheet.write(row, col + 5, adb_result)
        worksheet.write(row, col + 6, adb_confidence)
        worksheet.write(row, col + 7, "PASS")
        row += 1
    else:
        print(""+text_log+" -> FAIL")
        worksheet.write(row, col, adb_timestamp)
        worksheet.write(row, col + 1, adb_platform)
        worksheet.write(row, col + 2, adb_bspversion)
        worksheet.write(row, col + 3, text)
        worksheet.write(row, col + 4, text_log)
        worksheet.write(row, col + 5, adb_result)
        worksheet.write(row, col + 6, adb_confidence)
        worksheet.write(row, col + 7, "FAIL")
        workbook.close()  # will save the result till it executed in current script
        assert adb_result.lower() == text.lower()  # will terminate execution if failure occurs
        row += 1


def close_recent_applications():
    try:
        playsound('Tones/Recent Applications.wav')
        time.sleep(3)
        playsound('Tones/Dismiss All.wav')
        time.sleep(2)
        playsound('Tones/Navigate Back.wav')
    except:
        playsound('Tones/Recent Applications.mp3')
        time.sleep(3)
        playsound('Tones/Dismiss All.mp3')
        time.sleep(2)
        playsound('Tones/Navigate Back.mp3')


def device_wakeup():
    adb_wakeup = "adb shell input keyevent KEYCODE_WAKEUP"
    os.system(adb_wakeup)

def test_General_Setings_French():
    device_wakeup()
    close_recent_applications()
    time.sleep(2)

    # Network and Internet options testing
    voice_commands("Navigate Home","Menu Principal")
    time.sleep(2)
    voice_commands("My Programs","Mes Programmes")
    time.sleep(2)
    voice_commands("Setting","Paramètres")
    time.sleep(4)
    voice_commands("Network and Internet","Réseau et Internet")
    time.sleep(2)
    voice_commands("Wireless Networks","Wi Fi")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(3)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Connected devices","Appareils connectés")
    time.sleep(2)
    voice_commands("USB","USB")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Pair new device","Associer un appareil")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Connection preferences","Préférences de connexion")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Apps and notifications","Applis et notifications")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Battery","Batterie")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Display","Écran")
    time.sleep(2)
    voice_commands("Brightness level","Niveau de luminosité")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Night Light","Éclairage nocturne")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Screen timeout","Délai de mise en veille de l'écran")
    time.sleep(2)
    voice_commands("30 seconds","30secondes")
    time.sleep(2)
    voice_commands("Screen timeout","Délai de mise en veille de l'écran")
    time.sleep(2)
    voice_commands("5 minutes","5minutes")
    time.sleep(2)
    voice_commands("Screen timeout","Délai de mise en veille de l'écran")
    time.sleep(2)
    voice_commands("10 minutes","10minutes")
    time.sleep(2)
    voice_commands("Screen timeout","Délai de mise en veille de l'écran")
    time.sleep(2)
    voice_commands("30 minutes","30minutes")
    time.sleep(2)
    voice_commands("Screen timeout","Délai de mise en veille de l'écran")
    time.sleep(2)
    voice_commands("CANCEL","ANNULER")
    time.sleep(2)
    voice_commands("Page Down","Bas de page")
    time.sleep(2)
    voice_commands("Advanced","Préférences avancées")
    time.sleep(2)
    voice_commands("Font size","Taille de la police")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Sound","Son")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Page down","Bas de page")
    time.sleep(2)
    voice_commands("Storage","Stockage")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Privacy","Confidentialité")
    time.sleep(2)
    voice_commands("Accessibility usage","Utilisation de l'accessibilité")
    time.sleep(2)
    voice_commands("ok","OK")
    time.sleep(2)
    voice_commands("Permission manager","Gestionnaire d'autorisations")
    time.sleep(2)
    voice_commands("navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Show passwords","Afficher les mots de passe")
    time.sleep(2)
    voice_commands("Show passwords","Afficher les mots de passe")
    time.sleep(2)
    voice_commands("Lock screen","Écran de verrouillage")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Location","Localisation")
    time.sleep(2)
    voice_commands("Use Location","Utiliser ma position")
    time.sleep(2)
    voice_commands("Use Location","Utiliser ma position")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Security","Sécurité")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Accounts","Comptes")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Accessibility","Accessibilité")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Realwear","RealWear")
    time.sleep(2)
    voice_commands("Bluetooth Mode","Mode Bluetooth")
    time.sleep(2)
    voice_commands("Bluetooth Mode","Mode Bluetooth")
    time.sleep(2)
    voice_commands("Storage Mode","Mode de stockage")
    time.sleep(2)
    voice_commands("Storage Mode","Mode de stockage")
    time.sleep(2)
    voice_commands("Camera Low light","Caméra Basse Lumière")
    time.sleep(2)
    voice_commands("Camera Low light","Caméra Basse Lumière")
    time.sleep(2)
    voice_commands("Camera Field of View","Caméra champ de vision")
    time.sleep(2)
    voice_commands("Camera Field of View","Caméra champ de vision")
    time.sleep(2)
    voice_commands("Camera Image Stabilization","Caméra Stabilisation de l'image")
    time.sleep(2)
    voice_commands("Camera Image Stabilization","Caméra Stabilisation de l'image")
    time.sleep(2)
    voice_commands("Navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Page down","Bas de page")
    time.sleep(2)
    voice_commands("System","Système")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Select item 7","Sélectionnez l'élément 7")
    time.sleep(2)
    #voice_commands("Device name","nom de l'appareil")
    #time.sleep(4)
    #voice_commands("navigate Back","Retour En Arrière")
    #time.sleep(2)
    #voice_commands("Ok","ok")
    #time.sleep(2)
    #voice_commands("Cancel","annuler")
    #time.sleep(2)
    voice_commands("Emergency information","informations d'urgence")
    time.sleep(2)
    voice_commands("navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Model","modèle")
    time.sleep(2)
    voice_commands("navigate Back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Page Down","Bas de page")
    time.sleep(2)
    voice_commands("Android version","version d'android")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)
    voice_commands("Page Down","Bas de page")
    time.sleep(2)
    voice_commands("Build number","numéro de build")
    time.sleep(2)
    voice_commands("Navigate back","Retour En Arrière")
    time.sleep(2)

    workbook.close()